apiVersion: batch/v1
kind: Job
metadata:
  namespace: jenkins
  labels:
    app: mongo-init
  name: mongo-init-job
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mongo-init
        image: mongo:4.4
        command: ["mongo"]
        args:
          - "--host"
          - "mongo-ss-0.mongo.jenkins.svc.cluster.local:27017"
          - "--eval"
          - |
            rs.initiate({
              _id: "rs0",
              members: [
                { _id: 0, host: "mongo-ss-0.mongo.jenkins.svc.cluster.local:27017" },
                { _id: 1, host: "mongo-ss-1.mongo.jenkins.svc.cluster.local:27017" },
                { _id: 2, host: "mongo-ss-2.mongo.jenkins.svc.cluster.local:27017" }
              ]
            });
