apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-app
        image: deepaksag/springboot-mongodb:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: docker
        - name: SPRING_RABBITMQ_USERNAME
          value: admin
        - name: SPRING_RABBITMQ_PASSWORD
          value: admin
        - name: MEMCACHED_HOST
          value: memcached
        - name: MEMCACHED_PORT
          value: "11211"
        - name: SPRING_DATA_MONGODB_URI
          value: >-
                mongodb://mongo-ss-0.mongo.default.svc.cluster.local:27017,
                mongo-ss-1.mongo.default.svc.cluster.local:27017,
                mongo-ss-2.mongo.default.svc.cluster.local:27017/devopsdb?replicaSet=rs0

        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 20
          failureThreshold: 3
  
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: 8080
          initialDelaySeconds: 40
          periodSeconds: 10
          failureThreshold: 3
      
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: spring-app
spec:
  selector:
    app: spring-app
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer